### ISSUE TITLE
podspec?

### ISSUE THREAD

**Issue by hborders** [nschum/SwiftHamcrest#1]
Cocoapods supports swift as of 0.36 beta. Could you add a podspec and submit it to the Cocoapods specs repository please?

**Comment by nschum** [comment]
I added the podspec, but I don't think I can push it to the repository until 0.36 is released.

**Comment by hborders** [comment]
Why not? There are other swift libraries in the repo.

**Comment by nschum** [comment]
Because the linter stopped me from pushing.

Turns out that was just a [bug in CocoaPods](https://github.com/CocoaPods/trunk.cocoapods.org/pull/124).
