### ISSUE TITLE
Latest release does not build with new Swift (2.2)

### ISSUE THREAD

**Issue by codeslubber** [nschum/SwiftHamcrest#12]
Maybe you already know this. 

I am moving our project from CocoaPods to Carthage. Carthage requires a tag. The most recent one here is from last September. The following error occurs building it:

```
The following build commands failed:
    CompileSwift normal x86_64 /Users/robwilliams/Documents/workspaces/xcode/dminder-ios/Carthage/Checkouts/SwiftHamcrest/Hamcrest/Hamcrest.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
ft 3, please use #file
public func assertThrows<S, T: ErrorType where T: Equatable>(@autoclosure value: () throws -> S, _ error: T, file: String = __FILE__, line: UInt = __LINE__) -> String {

```

Xcode 7.3 was just released yesterday so maybe this was working.

**Comment by lukas2** [comment]
Hi, I've just run into the same issue. I've updated SwiftHamcrest to Swift 2.2, here's the pull request: https://github.com/nschum/SwiftHamcrest/pull/13

**Comment by nschum** [comment]
Sorry, dropped the ball on this due to Easter.
I'll get to it immediately.

**Comment by codeslubber** [comment]
I already forked and changed my carthage to point to my repo. There are 2 PRs here but the changes I needed to make were much more extensive.

**Comment by nschum** [comment]
done (still waiting for authentication email to upload pod, though)
