### ISSUE TITLE
Downcasting dictionary value

### ISSUE THREAD

**Issue by paiv** [nschum/SwiftHamcrest#15]
This is probably a Swift thing, but I don't get it:

``` swift
let dic: [String: AnyObject] = ["some": "value", "another": 1]

assertThat(dic, hasEntry(equalTo("some"), instanceOfAnd(equalTo("value"))))
assertThat(dic, hasEntry(equalTo("another"), instanceOfAnd(equalTo(1))))
```

I'm getting runtime error

```
fatal error: can't unsafeBitCast between types of different sizes
```

even before iteration of the dictionary begins.

Same thing here:

``` swift
let dic: [String: String] = ["some": "value", "another": "1"]

assertThat(dic, hasEntry(equalTo("some"), instanceOfAnd(equalTo("value"))))
```

**Comment by paiv** [comment]
The change in return type parameter seems to fix the issue:

``` swift
public func instanceOfAnd<T: Any, R: Any>(matcher: Matcher<T>) -> Matcher<R> {
    return Matcher("instance of \(T.self) and \(matcher.description)") {
        (value: Any) -> MatchResult in
        if let value = value as? T {
            return matcher.matches(value)
        } else {
            return .Mismatch("mismatched type")
        }
    }
}
```

But still, I'm not sure what is going on.

**Comment by renep** [comment]
I have added some tests to validate your problem, but with the current version I was unable to reproduce the issue. Maybe this was fixed during the Swift 3 migration.
Tests see: https://github.com/nschum/SwiftHamcrest/commit/6ad972a0c7dceaad6eea89c2cff7a246214893ed

**Comment by paiv** [comment]
I cannot reproduce this anymore. Hope everyone moved to Swift 3 by now.
Swift 3, Xcode 8.3
