### ISSUE TITLE
Swift 3 compatible release

### ISSUE THREAD

**Issue by renep** [nschum/SwiftHamcrest#25]
Is it possible to get an official release of SwiftHamcrest with Swift 3 support?

@nschum if you have not the time anymore to maintain this project, maybe you can grant access to someone else. e.g. @jonreid

**Comment by serges147** [comment]
I'm also interested in swift 3 release

**Comment by pikaboo** [comment]
+1

**Comment by renep** [comment]
@nschum has invited me to this project, so I will release a Swift 3 compatible version soon.
