### ISSUE TITLE
MacOS demo project does not compile

### ISSUE THREAD

**Issue by Bautastein** [nschum/SwiftHamcrest#44]
When trying to integrate SwiftHamcrest using Carthage, the cloned macOS demo project does not compile. Steps to reproduce:

1) Create Carthfile exactly as the one described on your `README.md` at the bottom
2) Run `carthage update --platform macOS`
3) Open cloned project `HamcrestDemo-macOS.xcodeproj` in XCode 10.1 (XCode 10.2 complains of swift 3.x files and tells us to use 10.1 instead).
4) Press `<command>-U` to build and run tests.

Expected result is successfully run tests
Actual result is the error: `No such module 'Hamcrest'`

**Comment by Bautastein** [comment]
I would like to add that after filing the issue, it occurred to me that there was also an xcworkspace in the SwiftHamcrest folder, and that maybe I was supposed to open that one instead. However, I can't run tests on the demos in this workspace neither in XCode 10.1, nor in XCode 10.2, because in XCode 10.1 it complains about unsupported swift version 5, and in XCode 10.2 it complains about unsupported swift version 3.

**Comment by renep** [comment]
For Xcode 10.1 and prior use the SwiftHamcrest version 2.1.
Version 2.2 is for Swift-5 and Xcode 10.2, this version does not work with 10.1.
Also update carthage to the latest 0.33 version.

**Comment by Bautastein** [comment]
Well, I am using Xcode 10.2, but it complained about Swift 3-code in the
macOS demo project, so I tried with Xcode 10.1 instead. The carthage
version is 0.33.0.

**Comment by renep** [comment]
Can you test the version from the `issue-44-macOS-Swift-5` branch. If it works, than I will create a new 2.2.1 release.

**Comment by Bautastein** [comment]
Yes, it works.

**Comment by renep** [comment]
Version 2.2.1 is available now.
