### ISSUE TITLE
Add 'reason' parameter to 'assertThat' function

### ISSUE THREAD

**Issue by adil-hussain-84** [nschum/SwiftHamcrest#51]
## Proposal

Add a `reason` optional parameter to the `assertThat(value:matcher:file:line:)` function to offer behaviour similar to the `reason` parameter in [Java Hamcrest's assertThat function](http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/MatcherAssert.html).

The `reason` parameter will allow the caller of the `assertThat` function to provide an additional, custom message to include in the test output in case the assertion fails.

## Example

A call to `assertThat(true, equalTo(false))` fails right now with a message:

```lang-none
failed - GOT: true, EXPECTED: equal to false
```
It would be great if I could call `assertThat(true, equalTo(false), reason: "Custom error message")` and see a failure message something like:

```lang-none
failed: Custom error message – GOT: true, EXPECTED: equal to false
```

**Comment by renep** [comment]
I thought of that already too. But I didn't found yet the time to implement this.

**Comment by adil-hussain-84** [comment]
@renep: Good to know you're okay with the idea in principle. I'll try find some time in the new few months to implement it and create a pull request.

**Comment by renep** [comment]
@adil-hussain-84 I have implemented this today and have named the parameter 'message'. You can check out the version in the develop branch is you like. I use this in one of my projects, to see if this works out fine before a do a new release.

**Comment by renep** [comment]
Released with version 2.2.3

**Comment by adil-hussain-84** [comment]
I just upgraded from SwiftHamcrest version 2.2.1 to 2.2.3 in one of my projects and I'm getting `"Variable binding in a condition requires an initializer"` Swift Compiler Errors on lines 109 and 111 of the [Hamcrest.swift](https://github.com/nschum/SwiftHamcrest/blob/master/Hamcrest/Hamcrest.swift) file.

I believe you need to change lines 109 to 111 from...

```lang-swift
if let possibleResult {
    let result: String
    if let message {
```

... to...

```lang-swift
if let possibleResult = possibleResult {
    let result: String
    if let message = message {
```

... for it to work in older versions of Swift.

**Comment by adil-hussain-84** [comment]
On a project which compiles with a newer version of Swift, the addition of the `message` parameter to the `assertThat` function works great 👍👍
