### ISSUE TITLE
SwiftHamcrest pod is not updated yet to use Swift 2.0

### ISSUE THREAD

**Issue by nourahassan** [nschum/SwiftHamcrest#7]
Latest version is 0.2.1 which is Swift 1.2, please we need a release for the new master code.

**Comment by nschum** [comment]
I will not release the Swift 2.0 version until Swift 2.0 is released. You should be able to use `:head` to get the Swift 2 code:

```
pod 'SwiftHamcrest', :head
```

**Comment by nourahassan** [comment]
Thank you.
