### ISSUE TITLE
Adopt semantic versioning

### ISSUE THREAD

**Issue by jonreid** [nschum/SwiftHamcrest#9]
Life goes better with http://semver.org, especially with CocoaPods

**Comment by nschum** [comment]
While I generally have reservations about semantic versioning, I'm actually using it here. :)

That's exactly why I have been hesitant to declare 1.0 and keep using 0.x. Swift compilers and syntax become obsolete so quickly that I see no value in worrying about backwards compatibility at the moment. Old versions won't even compile or link anymore. :)

It looks like Swift 3 will introduce some mechanisms for future-proofing frameworks. So hopefully we'll see enough language stability for a 1.0 then.

**Comment by jonreid** [comment]
OK. I assumed you weren't, since the latest release is 0.3 not 0.3.0.
